# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 291, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_2,
        )
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(
            self.verticalLayoutWidget_2,
        )
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_2.setRange(0, 20)
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.gridLayout.addWidget(self.doubleSpinBox_2, 3, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(
            self.verticalLayoutWidget_2,
        )
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox.setRange(0, 20)
        self.doubleSpinBox.setSingleStep(0.01)
        self.gridLayout.addWidget(self.doubleSpinBox, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(
            self.verticalLayoutWidget_2,
        )
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_3.setRange(0, 20)
        self.doubleSpinBox_3.setSingleStep(0.01)
        self.gridLayout.addWidget(self.doubleSpinBox_3, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.verticalSlider_3 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.verticalSlider_3.setRange(0, 2000)
        self.verticalSlider_3.setSingleStep(1)
        self.gridLayout.addWidget(self.verticalSlider_3, 0, 0, 1, 1)
        self.verticalSlider_2 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.verticalSlider_2.setRange(0, 2000)
        self.verticalSlider_2.setSingleStep(1)
        self.gridLayout.addWidget(self.verticalSlider_2, 0, 1, 1, 1)
        self.verticalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalSlider.setRange(0, 2000)
        self.verticalSlider.setSingleStep(1)
        self.gridLayout.addWidget(self.verticalSlider, 0, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_9.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_9.addWidget(self.checkBox_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.dial = QtWidgets.QDial(self.verticalLayoutWidget_2)
        self.dial.setObjectName("dial")
        self.dial.setRange(0, 20000)
        self.dial.setSingleStep(1)
        self.dial.setWrapping(False)
        self.dial.setNotchesVisible(True)
        self.dial.setNotchTarget(1000)
        self.horizontalLayout_9.addWidget(self.dial)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Minimum,
        )
        self.horizontalLayout_10.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(
            self.verticalLayoutWidget_2,
        )
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_4.setRange(0, 200)
        self.doubleSpinBox_4.setSingleStep(0.01)
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_4)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Minimum,
        )
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_11.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_11.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_11.addWidget(self.pushButton_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "P"))
        self.label_3.setText(_translate("MainWindow", "D"))
        self.label_2.setText(_translate("MainWindow", "I"))
        self.checkBox.setText(_translate("MainWindow", "PID调整"))
        self.checkBox_2.setText(_translate("MainWindow", "V速度控制"))
        self.label_4.setText(_translate(
            "MainWindow", "                                 V"),
        )
        self.label_5.setText(_translate(
            "MainWindow", "                         "),
        )
        self.pushButton_4.setText(_translate("MainWindow", "通讯"))
        self.pushButton_3.setText(_translate("MainWindow", "数据"))
        self.pushButton_2.setText(_translate("MainWindow", "控制"))
