# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import serial
import serial.tools.list_ports


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 291, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget,
        )
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_17.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_17.addLayout(self.horizontalLayout_2)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_17.addWidget(self.comboBox)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(
            0,
            QtWidgets.QFormLayout.LabelRole,
            self.label_2,
        )
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout_2.setWidget(
            0,
            QtWidgets.QFormLayout.FieldRole,
            self.comboBox_2,
        )
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(
            1,
            QtWidgets.QFormLayout.LabelRole,
            self.label_5,
        )
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout_2.setWidget(
            1,
            QtWidgets.QFormLayout.FieldRole,
            self.comboBox_3,
        )
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(
            2,
            QtWidgets.QFormLayout.LabelRole,
            self.label_6,
        )
        self.comboBox_4 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout_2.setWidget(
            2,
            QtWidgets.QFormLayout.FieldRole,
            self.comboBox_4,
        )
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(
            3,
            QtWidgets.QFormLayout.LabelRole,
            self.label_7,
        )
        self.comboBox_5 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout_2.setWidget(
            3,
            QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(
            4,
            QtWidgets.QFormLayout.LabelRole,
            self.label_8,
        )
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(
            4,
            QtWidgets.QFormLayout.FieldRole,
            self.pushButton,
        )
        self.verticalLayout_17.addLayout(self.formLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_17.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "串口选择"))
        port_list = list(serial.tools.list_ports.comports())
        if len(port_list) != 0:
            for i in range(len(port_list)):
                self.comboBox.addItem("")
                self.comboBox.setItemText(
                    i,
                    _translate("MainWindow", port_list[i][0]),
                )
                print(port_list[i][0])
        self.pushButton_5.setText(_translate("MainWindow", "刷新"))
        self.label_2.setText(_translate("MainWindow", "波特率"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "自定义"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "1382400"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "921600"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "460800"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "256000"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "230400"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "128000"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "115200"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "76800"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "57600"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "43000"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "38400"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "19200"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "14400"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "9600"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "4800"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "2400"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "1200"))
        self.label_5.setText(_translate("MainWindow", "停止位"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "1.5"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "2"))
        self.label_6.setText(_translate("MainWindow", "数据位"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "8"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "7"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "6"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "5"))
        self.label_7.setText(_translate("MainWindow", "奇偶校验"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "无"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "奇校验"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "偶校验"))
        self.label_8.setText(_translate("MainWindow", "串口操作"))
        self.pushButton.setText(_translate("MainWindow", "打开串口"))
        self.pushButton_4.setText(_translate("MainWindow", "通讯"))
        self.pushButton_3.setText(_translate("MainWindow", "数据"))
        self.pushButton_2.setText(_translate("MainWindow", "控制"))
